server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true #注册服务的IP，而不是服务器名称
  client:
    register-with-eureka: true #向Eureka注册服务
    fetch-registry: true #拉取注册表本地副本
    service-url:
      default-znoe: http://localhost:8761/eureka